### ISSUE TITLE
Can't append subsection to a subsection

### ISSUE THREAD

**Issue by ALIBRAGIMOV** [go-shiori/go-epub#16]
Processing of chapters into subchapters does not work correctly in the AddSubSection function, I get an error like ParentDoesNotExistError, I cannot correctly process more complex nesting.

**Comment by ALIBRAGIMOV** [comment]
check and run code from this link - [https://go.dev/play/p/1HJDpdJJyp-](url)

**Comment by ALIBRAGIMOV** [comment]
check and run code from this link - https://go.dev/play/p/1HJDpdJJyp-

**Comment by Monirzadeh** [comment]
Hi @ALIBRAGIMOV 
Thanks for your bug report, it is very helpful.
You can now add subsections wherever you want,
If there is any other problem, please give us feedback :+1:

**Comment by fmartingr** [comment]
Hey @Monirzadeh, remember to release a new version so people can use this on their project by using a version and not a commit sha.

**Comment by Monirzadeh** [comment]
> Hey @Monirzadeh, remember to release a new version so people can use this on their project by using a version and not a commit sha.

i try to review some of unit test and some improvement (some bug happen when we use custom name or specific custom name)
i try to release a new version as soon as possible,

**Comment by fmartingr** [comment]
> > Hey @Monirzadeh, remember to release a new version so people can use this on their project by using a version and not a commit sha.
> 
> i try to review some of unit test and some improvement (some bug happen when we use custom name or specific custom name) i try to release a new version as soon as possible 👍

👍 No rush at all! Just in case you forgot :)

**Comment by fmartingr** [comment]
> @fmartingr i create a milestone to not forgot that. `v1.3.0` or `v1.2.1`?

If this was a fix I'd go with a fix release (`v1.2.1`), if there were changes to public methods a minor (`v1.3.0`)

**Comment by ALIBRAGIMOV** [comment]
Hi 👋, thanks for your help with this problem 🙏.
