### ISSUE TITLE
is it possible to write []byte as a cover image? 

### ISSUE THREAD

**Issue by MarsSwimmer** [go-shiori/go-epub#34]
hi,

is it possible to write []byte as a cover image? 

in my process it get image from network, and i dont want to store on disk, just on ram, after use to epub, the image will recycle.

**Comment by MarsSwimmer** [comment]
oh, i know this solution after reading doc, 

but sometime we cant do network request, or network is unstable, if there already exist a image buffer, we can use []byte to set cover image or content image.

**Comment by MarsSwimmer** [comment]
thanks reply,

its not the problem, infact img url need network request, if it already exist img buffer, such as []byte or io reader, its no need to get img from network or from disk.

ok, there is no need, maybe its difficult. thanks again~

**Comment by MrColorado** [comment]
Hey, had the same need and finally got it working, a [data URL](https://wiki.penguinmod.com/wiki/Data_URL) (I discovered what it is today) as written inside the documentation does the job:

```
src := "data:image/jpeg;base64," + base64.StdEncoding.EncodeToString(coverBytes)
coverPath, err := e.AddImage(src, "cover.jpg")
```

Careful, the ;base64 part is mandatory without it there's no error, but the reader shows no cover.
